//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iniciar.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int no_cliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public decimal telefono { get; set; }
        public string sexo { get; set; }
        public bool account { get; set; }
    }
}
