//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iniciar.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int no_trasaccion { get; set; }
        public int no_cuenta { get; set; }
        public int tipo_trasaccion { get; set; }
        public decimal monto_trasaccion { get; set; }
    }
}
